name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^3.0.0
  flutter_rating_bar: ^4.0.1
  # google package
  scrollable_positioned_list: ^0.3.5
  equatable: ^2.0.5
  get_it: ^7.2.0
  api_core:
    path: ../api_core
  caching_service:
    path: ../caching_service

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  monarch: ^3.0.0
  very_good_analysis: ^4.0.0
  network_image_mock: ^2.1.1

flutter:
  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true
  assets:
    - ../api_core/assets/
    - assets/