name: clone_flix
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  envied: ^0.3.0
  flutter_platform_widgets: ^3.0.0
  intl: ^0.17.0
  get_it: ^7.2.0
  sheet: ^1.0.0-pre
  flex_color_scheme: ^7.0.1
  #---
  # downgrade until issue is fixed
  # https://github.com/flutter/flutter/issues/119798
  go_router: 5.2.4
  #---
  home_page:
    path: 'packages/home_page'
  detail_page:
    path: 'packages/detail_page'
  shared:
    path: 'packages/shared'
  my_video_player:
    path: 'packages/my_video_player'
  fluttertoast: ^8.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - packages/shared/assets/
    - .env
