name: my_video_player
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  video_player: ^2.6.1
  video_player_platform_interface_extra: ^5.0.1+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
