name: caching_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

# we have 2 packages with same version
isar_version: &isar_version 3.0.5

dependencies:
  flutter:
    sdk: flutter
  isar: *isar_version

dev_dependencies:
  build_runner: ^2.3.0
  isar_generator: *isar_version
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
